#add usb to telegraf?, Heimdal, pihole?
version: "3.3"
services:
  telegraf:
    container_name: Telegraf
    restart: always
    image: pauldheas/smartmeter:latest
    devices: 
    - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - ./Elektricity_meter.py:/home/Elektricity_meter.py
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '127.0.0.1:8125:8125/udp'
    tty: true
    environment: 
      - DOCKER_INFLUXDB_INIT_ORG=Meter
      - DOCKER_INFLUXDB_INIT_BUCKET=pi
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    networks:
      custom_network:
        ipv4_address: 172.19.0.2
  portainer:
    image: portainer/portainer:latest
    restart: always
    container_name: Portainer
    ports:
      - 9000:9000
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
  influxdb:
    container_name: InfluxDB
    restart: always
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=Meter
      - DOCKER_INFLUXDB_INIT_BUCKET=pi
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    networks:
      custom_network:
        ipv4_address: 172.19.0.3
  grafana:
    container_name: Grafana
    restart: always
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    networks:
      custom_network:
        ipv4_address: 172.19.0.4
volumes:
  influxdb-storage:
  grafana-storage:
  data:
networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16