#add usb to telegraf?, Heimdal, pihole?
version: "3.3"
services:
  telegraf:
    container_name: Telegraf
    restart: always
    ## not working at the moment needs to have the baudspeed set to 9200 and needs a changes of chmod
    image: telegraf:latest
    devices: 
    - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:r
    - ./Elektricity_meter.py:/home/Elektricity_meter.py:r
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '127.0.0.1:8125:8125/udp'
    environment: 
      - DOCKER_INFLUXDB_INIT_ORG=Meter
      - DOCKER_INFLUXDB_INIT_BUCKET=pi
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
  influxdb:
    container_name: InfluxDB
    restart: always
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=Meter
      - DOCKER_INFLUXDB_INIT_BUCKET=pi
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
  grafana:
    container_name: Grafana
    restart: always
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
volumes:
  influxdb-storage:
  grafana-storage: